# Generated by Django 5.2 on 2025-04-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_nickname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="login_id",
        ),
    ]
