# Generated by Django 5.2 on 2025-04-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_login_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.RemoveField(
            model_name="user",
            name="height",
        ),
        migrations.RemoveField(
            model_name="user",
            name="weight",
        ),
    ]
