# Generated by Django 5.2 on 2025-04-13 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_age_remove_user_height_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBiodata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "남성"),
                            ("female", "여성"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                ("resting_hr", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biodata",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
